# Generated by Django 3.2.12 on 2022-08-29 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='validationerror',
            options={'permissions': (('send_validation_error_resolution', 'Can send error resolution'), ('analyse_validation_error_resolution', 'Can analyse error resolution'))},
        ),
        migrations.CreateModel(
            name='ErrorResolutionOpinion',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last update date')),
                ('validation_error', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='analysis', serialize=False, to='upload.validationerror')),
                ('opinion', models.CharField(blank=True, choices=[('fixed', 'Fixed'), ('fix-demanded', 'Error has to be fixed')], max_length=32, null=True, verbose_name='Opinion')),
                ('comment', models.TextField(blank=True, max_length=512, null=True, verbose_name='Comment')),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='errorresolutionopinion_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='errorresolutionopinion_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Updater')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
